title: Khadas Documentation
subtitle: "Khadas Documentation."
description: "Khadas Documentation."
author: Khadas
language: en
timezone: PRC

url: https://docs.khadas.com
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

skip_render: vendor/**

theme: navy
deploy:
  type: git
  repo: git@github.com:khadas/khadas.github.io.git
  branch: master

highlight:
  enable: true
  line_number: true

google_analytics: UA-110196417-1
twitter: khadas_official
facebook: khadas.official
github: khadas
youtube: khadas
